# Generated by Django 3.2.7 on 2021-09-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='allowed_users',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chat',
            name='total_users',
            field=models.CharField(max_length=255),
        ),
    ]
