# Generated by Django 3.2.7 on 2021-09-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20210913_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='no_of_users',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
