# Generated by Django 3.2.7 on 2021-09-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_chat_no_of_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
